export const GET_TASKS_REQUEST = 'GET_TASKS_REQUEST';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';

export const GET_SUBTASKS_REQUEST = 'GET_SUBTASKS_REQUEST';
export const GET_SUBTASKS_SUCCESS = 'GET_SUBTASKS_SUCCESS';
export const GET_SUBTASKS_FAILURE = 'GET_SUBTASKS_FAILURE';
