
export let currentDate = new Date()
export let currentDay = currentDate.getDay() || 7
export let day1 = new Date(); day1.setDate(day1.getDate() - currentDay + 1)
export let day2 = new Date(); day2.setDate(day2.getDate() - currentDay + 2)
export let day3 = new Date(); day3.setDate(day3.getDate() - currentDay + 3)
export let day4 = new Date(); day4.setDate(day4.getDate() - currentDay + 4)
export let day5 = new Date(); day5.setDate(day5.getDate() - currentDay + 5)
export let day6 = new Date(); day6.setDate(day6.getDate() - currentDay + 6)
export let day7 = new Date(); day7.setDate(day7.getDate() - currentDay + 7)
export let day8 = new Date(); day8.setDate(day8.getDate() - currentDay + 8)
export let day9 = new Date(); day9.setDate(day9.getDate() - currentDay + 9)
export let day10 = new Date(); day10.setDate(day10.getDate() - currentDay + 10)
export let day11 = new Date(); day11.setDate(day11.getDate() - currentDay + 11)
export let day12 = new Date(); day12.setDate(day12.getDate() - currentDay + 12)
export let day13 = new Date(); day13.setDate(day13.getDate() - currentDay + 13)
export let day14 = new Date(); day14.setDate(day14.getDate() - currentDay + 14)
export let day15 = new Date(); day15.setDate(day15.getDate() - currentDay + 15)
export let thisWeek = [day1, day2, day3, day4, day5, day6, day7]
export let nextWeek = [day8, day9, day10, day11, day12, day13, day14]
export let fortNight = [day1, day2, day3, day4, day5, day6, day7, day8, day9, day10, day11, day12, day13, day14]